version: '3.1'

services:
  db:
    image: postgres:13.5
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: anton
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: db
  backend:
    build:
      context: ./TODO_project
    privileged: true
    expose:
      - 8080
    command: bash -c "
      python3 manage.py migrate
      && python3 manage.py create_users 3
      && gunicorn TODO_project.wsgi -b 0.0.0.0:8080
      "
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build:
      context: ./frontend_new
    ports:
      - 80:80
    depends_on:
      - nginx
