# Generated by Django 3.2.6 on 2021-11-11 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название проекта')),
                ('repo_link', models.CharField(max_length=256, verbose_name='ссылка на репозиторий')),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='авторы проекта')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок заметки')),
                ('text', models.TextField(blank=True, verbose_name='текст заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания заметки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления заметки')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор заметки')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TODO.project', verbose_name='проект заметки')),
            ],
        ),
    ]
