# Generated by Django 3.2.6 on 2021-11-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='active_tag',
            field=models.BooleanField(default=True, verbose_name='статус заметки'),
        ),
    ]
